version: "3.8"
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: clt2pjdb
      POSTGRES_USER: clt2pjuser
      POSTGRES_PASSWORD: clt2pjpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: .
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/clt2pjdb
      SPRING_DATASOURCE_USERNAME: clt2pjuser
      SPRING_DATASOURCE_PASSWORD: clt2pjpass
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      JWT_SECRET: dev_secret
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    command: [ "java", "-jar", "target/clt2pj-0.0.1-SNAPSHOT.jar" ]

volumes:
  postgres_data: