version: "3.9"

services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: clt2pjdb
      POSTGRES_USER: clt2pjuser
      POSTGRES_PASSWORD: clt2pjpass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
volumes:
  postgres_data:
