spring:
  profiles:
    active: dev

jwt:
  secret: "dev_secret"

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html