spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/clt2pjdb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: redis
      port: 6379

jwt:
  secret: ${JWT_SECRET}
server:
  port: 8080