spring:
  config:
    import: "optional:file:.env.development"

  datasource:
    url: jdbc:postgresql://localhost:5432/clt2pjdb
    username: clt2pjuser
    password: clt2pjpass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: redis
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - read:user
              - user:email

jwt:
  secret: 7dd2c499e70ba909ad18db766a8308abe602b0aaef259ceae2724ca960e4df35

server:
  port: ${SERVER_PORT:8080}