spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clt2pjdb
    username: clt2pjuser
    password: clt2pjpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: "dev_secret"
server:
  port: 8080